version: '3.8'

services:
  blood-donation-app:
    build: .
    container_name: blood_donation_system
    image: blood-donation-system
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data